Component({
    properties:{
        item:Object,
        type:String,
        opTime:String,
        dnNumber:String,
        sSite:String,
        eSite:String,
        number:String,
        isDetail:{
            type:Boolean,
            value:false
        }
    }
})
